# Generated by Django 5.1.6 on 2025-02-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='name',
            field=models.CharField(blank=True, default='No Name', max_length=500),
        ),
    ]
