# Generated by Django 5.1.6 on 2025-02-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_links_name'),
    ]

    operations = [
        migrations.RunSQL("UPDATE myapp_links SET name = 'Unnamed Link' WHERE name IS NULL;"),
    ]
    
