# Generated by Django 5.1.6 on 2025-02-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20250208_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
